### ISSUE TITLE
README.md shows `uspert` rather than `upsert`

### ISSUE THREAD

**Issue by wallentx** [keikoproj/aws-auth#16]
starting at the instructions here:
https://github.com/keikoproj/aws-auth/blob/master/README.md#user-content-usage-from-command-line:~:text=Bootstrap%20a%20new%20node%20group%20role,%24%20aws

Both of the references to `aws-auth upsert` say `aws-auth uspert`

**Comment by eytan-avisror** [comment]
Looks like we need to update our docs.
