### ISSUE TITLE
Krew plugin

### ISSUE THREAD

**Issue by jicowan** [keikoproj/aws-auth#30]
Would you consider making this a krew plugin?

**Comment by eytan-avisror** [comment]
Hi @jicowan 

We can probably add a krew plugin - if it can help someone don't see why not as long as we don't affect existing integration when running as lib/container. If that's something you'd like to contribute we'd be happy to take it 👍

**Comment by jicowan** [comment]
Thanks @eytan-avisror! I think all that I would need to do it create a yaml file for krew.  I'll look further into that.

I'm not sure it would work when running as a container though. I think krew expects a binary. That wouldn't preclude you from running aws-auth as a container if you preferred to use that option.

**Comment by eytan-avisror** [comment]
Yeah thats exactly what I meant, we would be able to run aws-auth in 3 ways:
- Import as a lib
- Run a container
- Use krew plugin

👍
