### ISSUE TITLE
--groups should not be required when doing upsert --maproles --rolearn --username

### ISSUE THREAD

**Issue by fizz** [keikoproj/aws-auth#7]
I don't have a particular group to add the role to, and k8s doesn't care when I edit manually. `aws-auth` forces me to specify a group, and inserts an empty list [] everywhere that I didn't used to have groups specified.

**Comment by eytan-avisror** [comment]
Hi @fizz 
Can you provide a sample invocation/code you are running, what the result is, and what you expect the result to be?

if I understand correctly, you want this utility to allow upser without `--groups`, for example:
```
aws-auth upsert --username test --maproles --rolearn role

- rolearn: role
      username: test
      groups: [].  <- groups is an empty list
``` 

Is this correct?
Can you explain the use case as well? what does it mean to add a role without groups?

**Comment by fizz** [comment]
Hi @eytan-avisror, 

That's almost correct. I'm looking for this:

```bash

aws-auth upsert --username test --maproles --rolearn role

  - rolearn: role
     username: test 
    # groups is entirely omitted
```

I'm adding a role without groups because it's intended to be used by a username, which is bound to a role that grants permissions on the cluster with a rolebinding.  I'm granting a Lambda permissions to create jobs in EKS. It works if I create it with `eksctl create iamidentitymapping`, and it works if I manually edit the configmap to add it. 

The only thing I really want is to be able to upsert without interactive editing, so I can do it with Jenkins. eksctl lacks this (it just keeps appending and filling my configmap with duplicate entries), but keikoproj/aws-auth offers it, and it's almost perfect for my use case.

**Comment by eytan-avisror** [comment]
Thanks @fizz 
This is doable, however, is there a functional difference between:
```
  - rolearn: role
    username: test 
    # groups is entirely omitted
```

And
```
  - rolearn: role
    username: test 
    groups: []
```
Trying to get a deeper understanding of the use-case here.

**Comment by eytan-avisror** [comment]
I think omitting groups should be as easy as simply adding `omitempty` to `Groups`

```
type UsersAuthMap struct {
	UserARN  string   `yaml:"userarn"`
	Username string   `yaml:"username"`
	Groups   []string `yaml:"groups,omitempty"`
}
```

**Comment by fizz** [comment]
> however, is there a functional difference

Probably not, but the aws-auth configmap is a shared resource in a shared EKS cluster, and multiple teams rely on it. I don't want to pollute it with a bunch of line-noise/empty groups. It also seems to suggest to a naive user that something is wrong, and that maybe groups should be created and added to the empty array.

**Comment by eytan-avisror** [comment]
@fizz makes sense, feel free to send a PR if you feel like adding the `omitempty` and testing it works as expected, otherwise I should be able to send one soon.
